# Medium alpha configuration

# 环境参数
env:
  num_agents: 8
  area_size: 1.0
  car_radius: 0.05
  comm_radius: 0.5
  mass: 0.1
  dt: 0.03
  cbf_alpha: 1.0  # 中等alpha值
  obstacles:
    enabled: true
    num_obstacles: 3
    obstacle_size: 0.15

# 网络参数
networks:
  policy:
    input_dim: 9
    node_dim: 7
    edge_dim: 4
    hidden_dim: 64
    n_layers: 2
    msg_hidden_sizes: [64, 64]
    aggr_hidden_sizes: [64]
    update_hidden_sizes: [64, 64]
  
  cbf:
    node_dim: 7
    edge_dim: 4
    hidden_dim: 64
    n_layers: 2
    msg_hidden_sizes: [64, 64]
    aggr_hidden_sizes: [64]
    update_hidden_sizes: [64, 64]

# 训练参数
training:
  training_steps: 10000
  horizon_length: 50
  eval_horizon: 100
  eval_interval: 100
  save_interval: 1000
  learning_rate: 0.001
  max_grad_norm: 1.0
  
  use_lr_scheduler: true
  lr_step_size: 2000
  lr_gamma: 0.5
  gradient_decay_rate: 0.95

  goal_weight: 1.0
  safety_weight: 10.0
  control_weight: 0.1
  jerk_weight: 0.05
  cbf_alpha: 1.0

device: "cpu"