
env:
  num_agents: 4
  area_size: 1.5
  car_radius: 0.05
  comm_radius: 0.5
  mass: 0.1
  dt: 0.05
  obstacles:
    enabled: false

training:
  training_steps: 100  # ³¬¶ÌÓ–¾š
  horizon_length: 10
  learning_rate: 0.01
  eval_interval: 50
  save_interval: 50
  
loss_weights:
  goal_weight: 1.0
  safety_weight: 2.0
  control_weight: 0.1
  jerk_weight: 0.02
  alpha_reg_weight: 0.01
  progress_weight: 0.2
