env:
  area_size: 1.0
  car_radius: 0.05
  cbf_alpha: 1.0
  comm_radius: 0.5
  dt: 0.03
  mass: 0.1
  num_agents: 6
networks:
  cbf:
    aggr_hidden_sizes:
    - 64
    edge_dim: 4
    hidden_dim: 64
    msg_hidden_sizes:
    - 64
    - 64
    n_layers: 2
    node_dim: 7
    update_hidden_sizes:
    - 64
    - 64
  policy:
    aggr_hidden_sizes:
    - 48
    edge_dim: 4
    hidden_dim: 48
    input_dim: 9
    msg_hidden_sizes:
    - 48
    - 48
    n_layers: 2
    node_dim: 7
    update_hidden_sizes:
    - 48
    - 48
run_name: SafetyGated_Accelerated_gpu
training:
  alpha_reg_weight: 0.01
  cbf_alpha: 1.0
  control_weight: 0.1
  eval_horizon: 100
  eval_interval: 200
  goal_weight: 1.0
  gradient_decay_rate: 0.95
  horizon_length: 30
  jerk_weight: 0.05
  learning_rate: 0.003
  lr_gamma: 0.5
  lr_step_size: 2000
  max_grad_norm: 1.0
  safety_loss_threshold: 0.01
  safety_weight: 10.0
  save_interval: 1000
  training_steps: 10000
  use_lr_scheduler: true
